export const HANDLE_LOGIN_MODAL = 'HANDLE_LOGIN_MODAL';
export const HANDLE_REGISTER_MODAL = 'HANDLE_REGISTER_MODAL';
export const CHECK_LOGIN = 'CHECK_LOGIN';
export const SHOW_ANOTHER_MODAL = 'SHOW_ANOTHER_MODAL';
export const LOG_OUT = 'LOG_OUT';
export const VIEW_PRODUCT_DETAIL = 'VIEW_PRODUCT_DETAIL';
export const VIEW_PRODUCTS_OF_CATEGORY = 'VIEW_PRODUCTS_OF_CATEGORY';

