export const HANDLE_LOGIN_MODAL = 'HANDLE_LOGIN_MODAL';
export const HANDLE_REGISTER_MODAL = 'HANDLE_REGISTER_MODAL';
export const CHECK_LOGIN = 'CHECK_LOGIN';
export const SHOW_ANOTHER_MODAL = 'SHOW_ANOTHER_MODAL';
export const LOG_OUT = 'LOG_OUT';
export const VIEW_PRODUCT_DETAIL = 'VIEW_PRODUCT_DETAIL';
export const VIEW_PRODUCTS_OF_CATEGORY = 'VIEW_PRODUCTS_OF_CATEGORY';
export const HANDLE_SELECTED_CATEGOGY = 'HANDLE_SELECTED_CATEGORY';
export const HANDLE_SELECTED_BRAND = 'HANDLE_SELECTED_BRAND';
export const HANDLE_SELECTED_COLOR = 'HANDLE_SELECTED_COLOR';
export const HANDLE_SELECTED_SIZE = 'HANDLE_SELECTED_SIZE';

export const HANDLE_CANCEL_PRODUCT = 'HANDLE_CANCEL_PRODUCT';
export const HANDLE_ADMIN_LOGIN = 'HANDLE_ADMIN_LOGIN';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CHECK_OUT = 'CHECK_OUT';







